### ISSUE TITLE
Some fields break with unicode characters

### ISSUE THREAD

**Issue by personthingman2** [startailcoon/Gridcoinstats-IssuesTracker#11]
I noticed this when I was looking through the [Whitepaper Proposal poll page](https://www.gridcoinstats.eu/poll/the_gridcoin_white_paper_proposal) and [found this user](https://i.imgur.com/9xv2OLu.png). It appears [some fields work while others don't](https://i.imgur.com/aG6NUqJ.png).

**Comment by startailcoon** [comment]
Thanks for noticing.

This has been an issue for me since the start and is because some users have non-latin characters in their usernames. The system I use for getting the data from BOINC servers aren't able to completely read this. 

I will continue to see how I can make this work.

**Comment by AllenChong** [comment]
issue
