### ISSUE TITLE
Voting commands 

### ISSUE THREAD

**Issue by startailcoon** [startailcoon/Gridcoinstats-IssuesTracker#12]
Voting commands on *nix requires command to be quoted.

Display voting command to include this as well. 

```
gridcoinresearchd execute vote Constant_Block_Reward_(CBR)_Proposal_and_Poll 85/15_with_a_5_GRC_block_reward

bash: syntax error near unexpected token `('```

**Comment by AllenChong** [comment]
gridcoinresearchd execute vote Constant_Block_Reward_(CBR)_Proposal_and_Poll 85/15_with_a_5_GRC_block_reward

bash: syntax error near unexpected token

**Comment by AllenChong** [comment]
issue
