### ISSUE TITLE
[Chain] Block Difficulty Changes

### ISSUE THREAD

**Issue by startailcoon** [startailcoon/Gridcoinstats-IssuesTracker#21]
Add safe checks to make sure we catch the new way that Difficulty is stored in the chain.

---
> It is very likely that we will change the difficulty in getinfo from
```
"difficulty": {
"proof-of-work": 12345,
"proof-of-stake": 12345
}
```
to
``"difficulty": 12345``

**Comment by w7788129** [comment]
Go
