### ISSUE TITLE
Fix the Faucet

### ISSUE THREAD

**Issue by sibebleuze** [startailcoon/Gridcoinstats-IssuesTracker#23]
The faucet has been down for a while now, giving people the message like in the picture below. However, some people obviously manage to still get payouts from the faucet, as the amount of GRC sent this month isn't 0. I think this is a problem that should be adressed.

![gridcoinstats faucet](https://user-images.githubusercontent.com/19614268/46995708-2979c080-d11a-11e8-9d88-272eb8975f68.PNG)

**Comment by startailcoon** [comment]
I can assure that nothing is sent out. Thoguh, for some reason users are able to circumvent the form still.

The faucet is going to be rewritten from scratch, but isn't something I've been able to do yet.

It's my wish to continue support the community.

**Comment by startailcoon** [comment]
The faucet is closed until the next version of the page is released in a few months
