### ISSUE TITLE
User details charts are not updating

### ISSUE THREAD

**Issue by JeffreyChamberlain** [startailcoon/Gridcoinstats-IssuesTracker#29]
My user details charts for RAC, Credit, and Magnitude are frozen at 2019.03.18 and have not updated since. 

![image](https://user-images.githubusercontent.com/49086526/55271618-02005580-526d-11e9-9749-025a4e78b1f4.png)

https://gridcoinstats.eu/cpid/7c983d00c42e4341277434b71b89861f

**Comment by d-s-spence** [comment]
Same for my CPID, and every other CPID that I checked.  It looks like none of the User Details charts are working.

**Comment by JeffreyChamberlain** [comment]
Yes, they seemed to have stopped working around the time the website was updated. Those were nice to track your progress it would be good to have them working again.

 

Jeff

**Comment by polpas** [comment]
My statistical graphs are frozen since 30 of august.
![Captura de ecrã 2019-11-01, às 21 47 15](https://user-images.githubusercontent.com/14005842/68058509-33546e80-fcf1-11e9-8d91-58713bf5640c.png)

**Comment by startailcoon** [comment]
The system for these graphs are in need of updates and will be fixed for the next major version of the page.
