### ISSUE TITLE
Incorrect calculation for the user's "Total Assets"?

### ISSUE THREAD

**Issue by DarrellStuff** [startailcoon/Gridcoinstats-IssuesTracker#30]
The calculation on the User CPID summary page showing the research Gridcoin DPoR Reward, PoS Interest and Transactions History for the user "ABC" with Boinc CPID <<CPID>> found at:

   https://gridcoinstats.eu/cpid/<<CPID>>

seems to be making an incorrect calculation for the user's Total Assets, as well as using an incorrect conversion constant for a USD value for each GRC owned.

In the case of:

   Total Assets | 3,698.14 GRC ($406,704.14)

calculating the USD value for GRC owned would be

   $406,704.14  (USD?)  /  3,698.14 GRC  =  $‭109.9753 per GRC.   (Really?)

Reversing the calculation results in:

3,698.14 GRC   /  $406,704.14   =  $‭0.009092948992356‬  per GRC.   (Better, but still off.)

There seems to be 2 problems.

First, the GRC to USD calculation for the web page seems to be dividing the GRC total by the current GRC-USD conversion value, instead of multiplying them together.

Second, as of today the value of GRC is currently around $0.003653 USD. This is about 1/3 of the value of $‭0.009093 used based on the reverse-calculated value shown above.

As of today, I would expect  3,698.14 GRC to be worth about $13.5093 USD. not around $406k.

**Comment by DarrellStuff** [comment]
In addition to fixing the assumed  /  vs  *  for the total assets calculation, please consider adding a line on the webpage showing the GRC-USD conversion value being used.  For example:

Note: The USD value of the "Total Assets" shown is based on 1 GRC = $0.003653 USD. This is an estimation only, please check current exchange rates for the actual market value of your GRC.

**Comment by startailcoon** [comment]
I will switch out the source of the price calculations as the exchanges used have likely stopped trading the coin, which caused these inaccurate prices
