### ISSUE TITLE
projects not beeing updated in active projects

### ISSUE THREAD

**Issue by polpas** [startailcoon/Gridcoinstats-IssuesTracker#32]
Projects added more than 2 weeks ago do not appear in my statistics in active projects.
The specific projects are:

rosetta@home
world community grid

team is correctly defined

**Comment by startailcoon** [comment]
One of the data collector scripts had stopped working. It should be fixed now

**Comment by polpas** [comment]
Rosetta@home is synced and in active projects but world community grid is not available. Would it be possible to check what is wrong? Would i need to open another issue or can it be in this ticket?

**Comment by startailcoon** [comment]
World Community Grid isn't available due to the changes in GDPR regulations.

This will be fixed on the next major version update of the page, in progress currently. Until then it will unfortunately not be possible to include it.
