### ISSUE TITLE
Implement Gridcoin Greylist Proposal

### ISSUE THREAD

**Issue by startailcoon** [startailcoon/Gridcoinstats-IssuesTracker#5]
This issue is a tracker for implementing the Gridcoin Greylist Proposal.

### Requested features

- Notifications when project status changes, to project whitelist maintainer
- Public JSON details
- Linkable image for display

**Comment by grcjamezz** [comment]
That would be a great idea if they did not butcher my Greylist ( originally called the project jail ) idea and have it half assed and manual bs like it is right now. 
I had hoped to see a website using an interface something like https://en.wikipedia.org/wiki/Xymon ( formerly known as bigbrother / bbmon ) but adapted to monitor projects WU counts and project websites for downtime , project server ip's for ping replys and set triggers for days a project is at 0 or under a certain number requirement threshold predetermined and adapt it for our needs. Could also do such with the addnode wiki list showing if a the listed nodes are up or down to show the state of the network status... Just an idea..

**Comment by w7788129** [comment]
Good
