### ISSUE TITLE
add team hosts

### ISSUE THREAD

**Issue by cymshah** [startailcoon/Gridcoinstats-IssuesTracker#7]
on the following webpage "https://www.gridcoinstats.eu/project" i would like to know if a column can be added for team hosts after the team users column?

**Comment by Dudebaker** [comment]
The assigned hosts do often not represent the real assigned hosts.
Some users have zero hosts but are in the top ten of the project contributors.
So it wouldn't be representative... you could use random numbers and have the same use. ;-)

**Comment by startailcoon** [comment]
Only computers not hidden from public are counted. If a user hides their computer stats we have an inaccurate count.

The hosts count/details are only useful on a user level.

**Comment by cymshah** [comment]
i see, didn't realize that the host counts were inaccurate.
